language: php

dist: xenial

services:
  - mysql
  - postgresql
  - xvfb

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy
      - chromium-chromedriver
      - chromium-browser

env:
  global:
    - DB=MYSQL
    - COMPOSER_ROOT_VERSION=1.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_TEST=1 COMPOSER_ARG=--prefer-lowest
    - php: 7.1
      env: BACKWARD_COMPAT=1 PHPUNIT_TEST=1 COMPOSER_ARG=--prefer-lowest
    - php: 7.2
      env: BEHAT_TEST=1
    - php: 7.2
      env: BEHAT_TEST=1 BACKWARD_COMPAT=1
    - php: 7.3
      env: PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1 PHPCS_TEST=1 BACKWARD_COMPAT=1
    - php: 7.4
      env: PHPUNIT_TEST=1
    - php: 7.1
      env: NPM_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1 DB=PGSQL
    - php: nightly
      env: PHPUNIT_TEST=1 COMPOSER_ARG=--ignore-platform-reqs WITH_XDEBUG=1

before_script:
# Extra $PATH
  - export PATH=/usr/lib/chromium-browser/:$PATH

# Init PHP
  - phpenv rehash
  - if [[ ! $WITH_XDEBUG ]] ; then phpenv config-rm xdebug.ini; fi
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer
  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.x-dev --prefer-dist; fi
  - composer require silverstripe/recipe-testing:^1 silverstripe/recipe-cms:4.x-dev silverstripe/frameworktest:4.x-dev --no-update --prefer-dist

######## Remove once GraphQL 4 is merged #########
  - composer require silverstripe/admin:"dev-pulls/1/schemageddon as 1.x-dev" silverstripe/cms:"dev-pulls/4/schemageddon as 4.x-dev" silverstripe/versioned-admin:"dev-pulls/1/schemageddon as 1.x-dev" silverstripe/versioned:"dev-pulls/1/schemageddon as 1.x-dev" silverstripe/graphql:"4.x-dev as 3.x-dev" --no-update
  - 'if [[ $BACKWARD_COMPAT ]]; then composer require silverstripe/graphql:"dev-pulls/3/schemageddon-compat as 3.x-dev" --no-update; fi'
##################################################

  - composer update $COMPOSER_ARG


# Remove preinstalled Chrome (google-chrome)
# this would conflict with our chromium-browser installation
# and its version is incompatible with chromium-chromedriver
  - sudo apt-get remove -y --purge google-chrome-stable || true

# Start behat services
  - if [[ $BEHAT_TEST ]]; then mkdir artifacts; fi
  - if [[ $BEHAT_TEST ]]; then cp composer.lock artifacts/; fi
  - if [[ $BEHAT_TEST ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
  - if [[ $BEHAT_TEST ]]; then (chromedriver > artifacts/chromedriver.log 2>&1 &); fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &); fi

# Install NPM dependencies
  - if [[ $NPM_TEST ]]; then rm -rf client/dist && nvm install && nvm use && npm install -g yarn && yarn install --network-concurrency 1 && (cd vendor/silverstripe/admin && yarn install --network-concurrency 1) && yarn run build; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run test; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @asset-admin; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_failure:
  - php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/
