version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-fixed-behat-npm.yml

env:
  global:
    - COMPOSER_ROOT_VERSION="1.x-dev"
    - REQUIRE_RECIPE="4.x-dev"
    - REQUIRE_FRAMEWORKTEST="0.4.2"
    - BEHAT_SUITE="asset-admin"
