---
Name: assetadmin
---
SilverStripe\CMS\Controllers\AssetAdmin:
  url_segment: 'old-assets'
SilverStripe\Assets\File:
  extensions:
    - 'SilverStripe\AssetAdmin\Controller\AssetAdminFile'
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\AssetAdmin\Controller\AssetAdminFieldsExtension
SilverStripe\GraphQL:
  schema:
    types:
      DataObjectInterface: 'SilverStripe\GraphQL\DataObjectInterfaceTypeCreator'
      File: 'SilverStripe\AssetAdmin\GraphQL\FileTypeCreator'
      FileInterface: 'SilverStripe\AssetAdmin\GraphQL\FileInterfaceTypeCreator'
      FileInput: 'SilverStripe\AssetAdmin\GraphQL\FileInputTypeCreator'
      Folder: 'SilverStripe\AssetAdmin\GraphQL\FolderTypeCreator'
      FolderInput: 'SilverStripe\AssetAdmin\GraphQL\FolderInputTypeCreator'
      FileFilterInput: 'SilverStripe\AssetAdmin\GraphQL\FileFilterInputTypeCreator'
    queries:
      readFiles: 'SilverStripe\AssetAdmin\GraphQL\ReadFileQueryCreator'
    mutations:
      createFile: 'SilverStripe\AssetAdmin\GraphQL\CreateFileMutationCreator'
      updateFile: 'SilverStripe\AssetAdmin\GraphQL\UpdateFileMutationCreator'
      deleteFile: 'SilverStripe\AssetAdmin\GraphQL\DeleteFileMutationCreator'
      createFolder: 'SilverStripe\AssetAdmin\GraphQL\CreateFolderMutationCreator'
