---
Name: assetadmin
---
SilverStripe\CMS\Controllers\AssetAdmin:
  url_segment: 'old-assets'
File:
  extensions:
    - 'SilverStripe\AssetAdmin\Controller\AssetAdminFile'
LeftAndMain:
  extra_requirements_javascript:
    - asset-admin/client/dist/js/bundle.js
